FROM node:20

RUN npm install -g fs-extra evolution-manager

RUN cd /usr/local/lib/node_modules/evolution-manager && npm install && npm run build

EXPOSE 3000

CMD ["evolution-manager", "server", "start", "--port=3000"]
