services:
  postgres:
    image: postgres:15-alpine
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - bot_network

  redis:
    image: redis:alpine
    container_name: chatbot_redis
    restart: always
    networks:
      - bot_network

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: always

    environment:
      - SERVER_URL=${EVOLUTION_API_URL}
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_TYPE=apikey
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379
      - CACHE_REDIS_PREFIX_KEY=evo
    depends_on:
      - postgres
      - redis
    volumes:
      - ./evolution-api/instances:/evolution/instances
    networks:
      - bot_network

  evolution-manager:
    image: atendai/evolution-manager:latest
    container_name: evolution_manager
    restart: always

    depends_on:
      - evolution-api
    networks:
      - bot_network

  bot-python:
    build: 
      context: .
    container_name: chatbot_python
    restart: always

    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
