FROM node:20

RUN ln -sf /usr/local/bin/npm /usr/bin/npm && \
    ln -sf /usr/local/bin/node /usr/bin/node

RUN npm install -g fs-extra evolution-manager

EXPOSE 3000

CMD ["evolution-manager", "server", "start", "--port=3000"]
